[book]
authors = ["jane"]
language = "en"
multilingual = false
src = "src"
title = "Time Machine"

[output.html]
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/jane-212/TimeMachine"

[output.html.fold]
enable = true
level = 2
